services:
    postgres:
      image: 'postgres:${PG_VERSION}'
      ports:
        - "${PG_PUB_PORT}:5432"
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_DB: ${PG_DATABASE}
      volumes:
        - ./docker/db-data/postgres/:/var/lib/postgresql/data/
    mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - "1025:1025"
        - "8025:8025"
      restart: unless-stopped